version: '3'

services:
  web:
    build: 
      context: ./Front_End
      dockerfile: Dockerfile
    container_name: WebPages
    ports:
      - "8000:80"
    networks:
      - default
  node:
    build:
      context: ./Back_End
      dockerfile: Dockerfile
    image: gabrielpellegrini/nodejs:TCC.8.11.2
    command: node app.js
    tty: true
    stdin_open: true
    container_name: node_app
    ports:
      - 3050:3000
    networks: 
      - default 
  mysql:
    image: mysql:5.7
    container_name: mysql_app
    tty: true
    stdin_open: true
    ports: 
      - 3306:3306
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_ROOT_PASSWORD=yourpassword
      - MYSQL_USER=user
    networks: 
      - default
networks:
  default: