version: '3'

services:
  web:
    build: 
      context: ./Front_End
      dockerfile: Dockerfile
    container_name: WebPages
    ports:
      - "8000:80"
    networks:
      - default
  node:
    build:
      context: ./Back_End
      dockerfile: Dockerfile
    image: gabrielpellegrini/nodejs:8.11.2
    command: nodemon app.js
    tty: true
    stdin_open: true
    container_name: node_app
    ports:
      - 3050:3000
    volumes:
      - .:/home/app/portal
      - /home/app/portal/node_modules
    networks: 
      - default 
  mysql:
    image: mysql:5.6
    container_name: mysql_app
    tty: true
    stdin_open: true
    ports: 
      - 3306:3306
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_ROOT_PASSWORD=yourpassword
    networks: 
      - default
    volumes:
      - ./DB/Data:/var/lib/mysql
networks:
  default:
